version: 0.2

run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - apt-get update && apt-get install awscli
      - cd $CODEBUILD_SRC_DIR
      - npm run install:all
  build:
    commands:
      - npm run test:upload
cache:
  paths:
    - '**/*/node_modules'